name: Deploy Kivy App to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Pygbag and Build Web Assets
        run: |
          pip install pygbag
          # Compiles main.py straight into web elements
          python -m pygbag --build .

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: deploy-pages@v4
